version: "3"
services:
  nginx:
    build: ./
    ports:
    - "8888:8080"
    volumes:
    - "./nginx_lua/:/opt/app/"
    - "./ebooks:/opt/ebooks"
    - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"